version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: mna_tax_neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-password}

volumes:
  neo4j_data:
